services:
  - type: web
    name: washatdoor
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: PORT
        value: 5000
      - key: NPM_CONFIG_PRODUCTION
        value: false 